services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "1883:1883" #PUERTO DEFAULT PARA ESCUCHAR MQTT
      - "5672:5672" #PUERTO DEFAULT PARA ESCUCHAR DEF AMQP
      - "15672:15672" #PUERTO DEFAULT PARA ADMINISITRADOR
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: event_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-event/init.sql:/docker-entrypoint-initdb.d/init.sql
      
volumes:
  rabbitmq_data:
  postgres_data: